/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lecturer;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author imalkesara
 */
public class Attendance extends javax.swing.JFrame {

    /**
     * Creates new form Attendance
     */
    
    AttendanceEligibility attendanceEligibility = new AttendanceEligibility();
    private DefaultTableModel model;
    
    public Attendance() {
        initComponents();
        init();
    }
    
    public void init(){
        tableAttendanceEligibility();
    }
    
    private void tableAttendanceEligibility(){
        attendanceEligibility.getStudentAttendance(AttendanceEli, "");
        model = (DefaultTableModel) AttendanceEli.getModel();
        AttendanceEli.setRowHeight(30);
        AttendanceEli.setShowGrid(true);
        AttendanceEli.setGridColor(Color.black);
        AttendanceEli.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Eligibile = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AttendanceEli = new javax.swing.JTable();
        ESearch = new javax.swing.JButton();
        EBtn = new javax.swing.JButton();
        Ebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(96, 165, 250));

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search Course Code / Student ID :");

        AttendanceEli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Course Code", "Session Type", "80%  Percentage", "Eligiblity"
            }
        ));
        AttendanceEli.setGridColor(new java.awt.Color(153, 153, 255));
        AttendanceEli.setRowMargin(5);
        jScrollPane1.setViewportView(AttendanceEli);

        ESearch.setBackground(new java.awt.Color(4, 8, 15));
        ESearch.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        ESearch.setForeground(new java.awt.Color(255, 255, 255));
        ESearch.setText("Search");
        ESearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ESearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESearchActionPerformed(evt);
            }
        });

        EBtn.setBackground(new java.awt.Color(4, 8, 15));
        EBtn.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        EBtn.setForeground(new java.awt.Color(255, 255, 255));
        EBtn.setText("Refresh");
        EBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        EBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EBtnActionPerformed(evt);
            }
        });

        Ebtn.setBackground(new java.awt.Color(4, 8, 15));
        Ebtn.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        Ebtn.setForeground(new java.awt.Color(255, 255, 255));
        Ebtn.setText("Back");
        Ebtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Ebtn.setBorderPainted(false);
        Ebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EbtnMouseClicked(evt);
            }
        });
        Ebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Eligibile)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ESearch, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(EBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eligibile, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ESearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ESearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESearchActionPerformed
        if(Eligibile.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a corsecode");
        }else{
            AttendanceEli.setModel(new DefaultTableModel(null, new Object[]{"Student ID", "Course Code", "Session Type", "80% Precentage", "Eligiblity"}));
            attendanceEligibility.getStudentAttendance(AttendanceEli, Eligibile.getText());

        }
    }//GEN-LAST:event_ESearchActionPerformed

    private void EBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EBtnActionPerformed
        if(Eligibile.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a corsecode");
        }else{
            AttendanceEli.setModel(new DefaultTableModel(null, new Object[]{"Student ID", "Course Code", "Session Type", "80% Precentage", "Eligiblity"}));
            attendanceEligibility.getStudentAttendance(AttendanceEli, "");
        }     
    }//GEN-LAST:event_EBtnActionPerformed

    private void EbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EbtnMouseClicked
        setVisible(false);
    }//GEN-LAST:event_EbtnMouseClicked

    private void EbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EbtnActionPerformed

    }//GEN-LAST:event_EbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AttendanceEli;
    private javax.swing.JButton EBtn;
    private javax.swing.JButton ESearch;
    private javax.swing.JButton Ebtn;
    private javax.swing.JTextField Eligibile;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
